Models/Kayttaja.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace KoodinenV1.Models
{
    public partial class Kayttaja
    {
        public Kayttaja()
        {
            KurssiSuoritus = new HashSet<KurssiSuoritu>();
            Kurssis = new HashSet<Kurssi>();
            OppituntiSuoritus = new HashSet<OppituntiSuoritu>();
            TehtavaSuoritus = new HashSet<TehtavaSuoritu>();
        }

        public int KayttajaId { get; set; }
        public string Nimi { get; set; }
        public string Email { get; set; }
        public string Salasana { get; set; }
        public bool OnAdmin { get; set; }

        public virtual ICollection<KurssiSuoritu> KurssiSuoritus { get; set; }
        public virtual ICollection<Kurssi> Kurssis { get; set; }
        public virtual ICollection<OppituntiSuoritu> OppituntiSuoritus { get; set; }
        public virtual ICollection<TehtavaSuoritu> TehtavaSuoritus { get; set; }
    }
}

Models/ProfiiliViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KoodinenV1.Models
{
    public class ProfiiliViewModel
    {
        public string Nimi { get; set; }
        public DateTime? SuoritusPVM { get; set; }
        public int? KurssiId { get; set; }
        //public string Kuvaus { get; set; }

    }
}

Models/SalasananVaihtoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KoodinenV1.Models
{
    public class SalasananVaihtoViewModel
    {
        [DataType(DataType.Password)]
        [Display(Name = "Nykyinen salasana")]
        public string VanhaSalasana { get; set; }

        [StringLength(100, ErrorMessage = "Salasanan on oltava vähintään {2} merkkiä pitkä,\nja sen tulee sisältää ainakin yksi pieni ja suuri\nkirjain sekä numero.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Uusi salasana")]
        public string UusiSalasana { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Vahvista uusi salasana")]
        [Compare("UusiSalasana", ErrorMessage = "Salasanat eivät täsmää.")]
        public string VahvistusSalasana { get; set; }

        public int Id { get; set; }
    }
}

Controllers/AdminController.cs
using KoodinenV1.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KoodinenV1.Controllers
{
    public class AdminController : Controller
    {KoodinenDBContext _context;

        public AdminController(KoodinenDBContext context)
        {
            _context = context;
        }

        public IActionResult AdminPääsivu()
        {
            int? id = HttpContext.Session.GetInt32("id");
            if (id == null)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            if (_context.Kayttajas.Where(k => k.KayttajaId == id).Select(x => x.OnAdmin).FirstOrDefault() != true)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            var kurssi = _context.Kurssis.Find(4);
            return View(kurssi);
        }
        public IActionResult Oppitunti1()
        {
            int? id = HttpContext.Session.GetInt32("id");
            if (id == null)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            if (_context.Kayttajas.Where(k => k.KayttajaId == id).Select(x => x.OnAdmin).FirstOrDefault() != true)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            return View();
        }
        public IActionResult Oppitunti3(int kurssiId = 4)
        {
            int? id = HttpContext.Session.GetInt32("id");
            if (id == null)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            if (_context.Kayttajas.Where(k => k.KayttajaId == id).Select(x => x.OnAdmin).FirstOrDefault() != true)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            AdminViewModel AVM = new AdminViewModel() 
            { 
                Ohje = _context.Ohjeistus.Where(o => o.OppituntiId == 11).First(), 
                Tehtävät = _context.Tehtavas.Where(t => t.OppituntiId == 11).ToList(),
                Kurssi = _context.Kurssis.Find(kurssiId)
            };

            return View(AVM);
        }
        public IActionResult MuokkaaTehtava(int tehtäväId)
        {
            int? id = HttpContext.Session.GetInt32("id");
            if (id == null)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            if (_context.Kayttajas.Where(k => k.KayttajaId == id).Select(x => x.OnAdmin).FirstOrDefault() != true)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            var tehtävä = _context.Tehtavas.Find(tehtäväId);
            return View(tehtävä);
        }
        [HttpPost]
        public IActionResult MuokkaaTehtava(Tehtava tehtävä)
        {
            int? id = HttpContext.Session.GetInt32("id");
            if (id == null)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            if (_context.Kayttajas.Where(k => k.KayttajaId == id).Select(x => x.OnAdmin).FirstOrDefault() != true)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            var teht = _context.Tehtavas.Where(t => t.TehtavaId == tehtävä.TehtavaId).FirstOrDefault();
            teht.Kuvaus = tehtävä.Kuvaus;
            _context.SaveChanges();
            ViewBag.Viesti = "Tehtävän muokkaus onnistui!";
            return View(tehtävä);
        }
    }




}

Controllers/KayttajaController.cs
using KoodinenV1.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KoodinenV1.Controllers
{
    public class KayttajaController : Controller
    {

        private readonly ILogger<RekisteröityminenController> _logger;

        private readonly KoodinenDBContext _context;


        private readonly IConfiguration _configuration;


        public KayttajaController(ILogger<RekisteröityminenController> logger, KoodinenDBContext context, IConfiguration configuration)
        {
            _logger = logger;
            _context = context;
            _configuration = configuration;
        }


        public IActionResult Profiili(string viesti = null)
        {
            int id = HttpContext.Session.GetInt32("id") ?? 0;
            if (id == 0)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            Apumetodit am = new Apumetodit(_context);
            var käyttäjä = am.HaeKäyttäjä(id);

            if (id == 0)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }

            var suoritetut = (from x in _context.KurssiSuoritus
                              join k in _context.Kurssis on x.KurssiId equals k.KurssiId
                              where x.KayttajaId == id && x.Kesken == false
                              orderby x.SuoritusPvm
                              select new ProfiiliViewModel { Nimi = k.Nimi, SuoritusPVM = x.SuoritusPvm }).ToList();

            var aloitettu = (from x in _context.KurssiSuoritus
                          join k in _context.Kurssis on x.KurssiId equals k.KurssiId
                          where x.KayttajaId == id && x.Kesken == true
                          orderby x.SuoritusPvm
                          select new ProfiiliViewModel{ Nimi = k.Nimi, KurssiId = x.KurssiId}).ToList();


            if (viesti != null)
            {
                ViewBag.Viesti = viesti;
            }

            ViewBag.aloitettu = aloitettu;
            ViewBag.suoritetut = suoritetut;

            return View(käyttäjä);

        }
        public async Task<IActionResult> Muokkaa()
        {
            int id = HttpContext.Session.GetInt32("id") ?? 0;
            if (id == 0)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            //if (id == null)
            //{
            //    return NotFound();
            //}

            var kayttaja = await _context.Kayttajas.FindAsync(id);
            if (kayttaja == null)
            {
                return NotFound();
            }
            return View(kayttaja);
        }

        // POST: People/Edit/5
        /// Lähettää kirjautuneen henkilön pävitetyt tiedot muokkauksen lomakkeesta
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Muokkaa(string nimi, string email)
        {
            int id = HttpContext.Session.GetInt32("id") ?? 0;
            if (id == 0)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            Apumetodit am = new Apumetodit(_context);
            var kayttaja = am.HaeKäyttäjä(id);
            if (kayttaja == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (nimi.Length >= 100)
                {
                    ModelState.AddModelError("Nimi", "Nimi on liian pitkä!");
                    return View();
                }
                if (email.Length >= 100)
                {
                    ModelState.AddModelError("Email", "Sähköpostiosoite on liian pitkä!");
                    return View();
                }
                try
                {
                    kayttaja.Nimi = nimi;
                    kayttaja.Email = email;
                    _context.Update(kayttaja);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!am.KäyttäjäOnOlemassa(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Profiili), new { id = id });
            }
            return View(kayttaja);
        }

        public async Task<IActionResult> SalasananVaihto()
        {
            int id = HttpContext.Session.GetInt32("id") ?? 0;
            if (id == 0)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }
            //if (id == null)
            //{
            //    return NotFound();
            //}
            var kayttaja = await _context.Kayttajas.FindAsync(id);
            if (kayttaja == null)
            {
                return NotFound();
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SalasananVaihto(SalasananVaihtoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            Apumetodit am = new Apumetodit(_context);
            model.Id = (int)HttpContext.Session.GetInt32("id");
            var salasana = am.HaeKäyttäjä(model.Id).Salasana;
            if (am.HashSalasana(model.VanhaSalasana) != salasana)
            {
                ModelState.AddModelError("SalasananVaihto", "Vanha salasana on väärin");
                return View();
            }
            if (model.UusiSalasana.Length >= 50)
            {
                ModelState.AddModelError("UusiSalasana", "Salasana on liian pitkä!");
                return View();
            }
            if (!am.SalasanaHyväksytyssäMuodossa(model.UusiSalasana))
            {
                ModelState.AddModelError("SalasananVaihto", "Salasanan on oltava vähintään 6 merkkiä pitkä,\nja sen tulee sisältää ainakin yksi pieni ja suuri\nkirjain sekä numero.");
                return View();
            }
            if (am.VaihdaSalasana(model.Id, model.UusiSalasana))
            {
                string viesti = "Salasana vaihdettu onnistuneesti!";
                return RedirectToAction("Profiili", null, new { viesti }, null);
            }
            ViewBag.Viesti = "Jokin meni pieleen, yritä uudelleen. Jos ongelma toistuu, ota yhteyttä ylläpitoon.";
            return View();
        }
        public IActionResult KurssistaAloitetut(int kurssiId)
        {
            int id = HttpContext.Session.GetInt32("id") ?? 0;
            Apumetodit am = new Apumetodit(_context);
            if (id == 0)
            {
                return RedirectToAction("Kirjautuminen", "Etusivu");
            }

            var käyttäjä = _context.Kayttajas.Where(k => k.KayttajaId == id).FirstOrDefault();
            var oppitunnit = _context.Oppituntis.Where(k => k.KurssiId == kurssiId).ToList();
            List<Tehtava> tehtavat = new List<Tehtava>();
            foreach(var oppitunti in oppitunnit)
            {
                tehtavat.AddRange(_context.Tehtavas.Where(o => o.OppituntiId == oppitunti.OppituntiId).ToList());
            }

            List<int?> suoritetutTehtavat = _context.TehtavaSuoritus.Where(k => k.KayttajaId == id).Select(x => x.TehtavaId).ToList();
            
            KurssistaAloitettuViewModel KAVM = new KurssistaAloitettuViewModel()
            {
                Kurssi = _context.Kurssis.Find(kurssiId),
                Oppitunnit = oppitunnit,
                Tehtävät = tehtavat,
                Suoritetut = suoritetutTehtavat
            };

            return View(KAVM);
        }

    }
}

Views/Kayttaja/KurssistaAloitetut.cshtml
@model KoodinenV1.Models.KurssistaAloitettuViewModel
@{
    ViewData["Title"] = "KurssistaAloitetut";

}

<h2 style="color: rgb(4, 115, 100)">Kurssin @Model.Kurssi.Nimi sisältö:</h2>
<hr />
@for (var i = 0; i < Model.Oppitunnit.Count; i++)
{
    {
        var oppitunti = Model.Oppitunnit[i];
        <h4>@Html.ActionLink(oppitunti.Nimi, $"Oppitunti{i+1}", Model.Kurssi.Nimi)</h4>
        @foreach (var tehtava in Model.Tehtävät)
        {
            @if (tehtava.OppituntiId == oppitunti.OppituntiId)
            {
                <p>
                    <b>  @tehtava.Kuvaus</b> @if (Model.Suoritetut.Contains(tehtava.TehtavaId))
                    {<partial><strong style="color:mediumseagreen;font-size:20px">&#10003;</strong></partial>}
                </p>
            }
        }
    }
}

Views/Kayttaja/KurssistaSuoritetut.cshtml
@model KoodinenV1.Models.Kayttaja
@{
    ViewData["Title"] = "KurssistaSuoritetut";
    var kurssinimi = ViewBag.kurssinimi;
    var oppitunnit = ViewBag.oppitunnit;
    var tehtävät = ViewBag.tehtävät;
    var nimi = ViewBag.nimi;
    //var id = ViewBag.id;
}
@*<div style='float:right;'>Hello @Html.ActionLink(firstName, "Profiili", "Kayttaja", new { id = id })</div>
    <br />
    <div style='float:right;'>@Html.ActionLink("Kirjaudu ulos", "", "")</div>*@
<style>
    # oppitunti {
        font-weight: bold;
        display: inline;
    }
</style>
<h3>Kurssista @kurssinimi suoritetut:</h3>

<h6 style="color:blue;">Oppitunnit</h6>
<ul>
    @foreach (var item in oppitunnit)
    {
        <ul id="oppitunti">
            <li>
                <strong>@item.Nimi:</strong> @item.Kuvaus
            </li>
        </ul>

    }

</ul>
<h6 style="color:blue;">Tehtävät</h6>
<ul>
    @foreach (var item in tehtävät)
    {
        <ul id="oppitunti">
            <li>
                <strong>@item.Nimi:</strong> @item.Kuvaus
            </li>
        </ul>
    }
</ul>
<br />
<br />
<div>
    <a asp-action="Edit" asp-route-id="@Model.KayttajaId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Kayttaja/Muokkaa.cshtml
@model KoodinenV1.Models.Kayttaja

@{
    ViewData["Title"] = "Muokkaa";
}

<h1>Muokkaa</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Muokkaa">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="KayttajaId" />
            <div class="form-group">
                <label asp-for="Nimi" class="control-label">Nimi: </label>
                <input asp-for="Nimi" class="form-control" />
                <span asp-validation-for="Nimi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Sähköposti</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            @*<div display="none" class="form-group">
                <label asp-for="Salasana" class="control-label">Nykyinen salasana: </label>
                <input asp-for="Salasana" class="form-control" type="password" />
                <span asp-validation-for="Salasana" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                
            </div>   
            <div class="form-group">
                <input type="submit" value="Tallenna" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Takaisin profiiliin", "Profiili")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Kayttaja/Profiili.cshtml
@model KoodinenV1.Models.Kayttaja

@{
    ViewData["Title"] = "Profiili";
    var suoritetut = ViewBag.suoritetut;
    var aloitettu = ViewBag.aloitettu;

}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<style>
    #otsikot {
        font-weight: bold;
        color: blue;
    }
</style>
<h3>Profiili</h3>

<div>
    <hr />
    @if (ViewBag.Viesti != null)
    {
        <h6 style="color: red">@ViewBag.Viesti</h6>
    }
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nimi)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nimi)
        </dd>
        <dt class="col-sm-2">
            Sähköposti
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>

<table>
    <tr>
        <td>
            <div>
                <a class="btn btn-outline-primary" asp-action="Muokkaa" asp-route-id="@Model.KayttajaId">Muokkaa</a>
            </div>
        </td>
        <td>
            <div>
                <a class="btn btn-outline-primary" asp-action="SalasananVaihto" asp-route-id="@Model.KayttajaId">Vaihda salasana</a>
            </div>
        </td>
    </tr>
</table>
<br />
<br />
<h6 class="otsikot">Suoritetut kurssit</h6>
<br />
@if (suoritetut.Count == 0)
{
    <li>Ei suoritettuja kursseja.</li>
}
else
{
    foreach (var item in suoritetut)
    {
        <li>
            <strong>Suoritettu: </strong> @Html.ActionLink($"{@item.Nimi} / {@item.SuoritusPVM.ToShortDateString()}", "Esittely", $"{@item.Nimi}")
        </li>
    }
}

<br />
<br />
<h6 class="otsikot">Aloitetut kurssit:</h6>
<br />
@if (aloitettu == null)
{
    <li>Ei suoritettuja kursseja.</li>
}
else
{
    @foreach (var item in aloitettu)
    {
        @*<li>
            @Html.ActionLink($"{@item.Nimi}", "KurssistaAloitetut", "Kayttaja") 
        </li>*@
        <li>
            @Html.ActionLink($"{@item.Nimi}", "KurssistaAloitetut", "Kayttaja", new {kurssiId = item.KurssiId })
        </li>
    }
}
@if (Model.OnAdmin == true)
            {
    <hr />
                <h6>@Html.ActionLink("Admin sivuille", "AdminPääsivu", "Admin")</h6>
                
            }

Views/Kayttaja/SalasananVaihto.cshtml
@model KoodinenV1.Models.SalasananVaihtoViewModel
@{
    ViewBag.Title = "Salasanan vaihto";
}

<h1>@ViewBag.Title</h1>

@using (Html.BeginForm("SalasananVaihto", "Kayttaja", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.VanhaSalasana, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.VanhaSalasana, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.UusiSalasana, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.UusiSalasana, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.VahvistusSalasana, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.VahvistusSalasana, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Vaihda salasana" class="btn btn-primary" />
        </div>
        <p>@ViewBag.Viesti</p>
    </div>
    <div>
        @Html.ActionLink("Takaisin profiiliin", "Profiili")
    </div>
}